### ISSUE TITLE
Hash of SWaT_Dataset_Attack_v0.csv has changed

### ISSUE THREAD

**Issue by NanaManiac** [pwwl/ics-anomaly-attribution#3]
Hi there,

Thank you for the source code. However I get this error w.r.t processing SWaT:

IMPORTANT: the hash of SWaT_Dataset_Attack_v0.csv has changed from the expected hash, meaning process_SWaT.py will no longer function correctly.
Please submit an Issue at https://github.com/pwwl/ics-anomaly-detection/issues/ to make us aware that the SWaT dataset has changed. Sorry for the inconvenience!

Seek your kind help regarding this.

Cheers!

**Comment by NanaManiac** [comment]
Strange, now it works. Thanks though!

**Comment by abudeeb** [comment]
I had the same issue, It turns out that I was saving it as a UTF-8 encoded CSV file. Save it a non encoded it should work just fine
